import fs from 'node:fs';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { operations, toolName } from '../automation/catalog';
const lines = [
  '---',
  'title: MCP / CLI 操作参考',
  'sidebar_position: 21',
  '---',
  '',
  '<!-- Generated by npm run docs:automation. Do not edit by hand. -->',
  '',
  `共 ${operations.length} 个操作。CLI 和 MCP 共用以下输入结构。异步操作返回任务 ID，通过 \`tasks.get\` / \`tasks.wait\` 获取结果；MCP 将结果放在 \`structuredContent.result\`。`,
  '',
  '配置对象中 additionalProperties=true 表示支持应用原有高级字段；服务端仍执行对应业务校验。服务商字段请调用 providers.types 查询。',
  '',
];
for (const op of operations) {
  lines.push(
    `## ${op.name}`,
    '',
    op.description,
    '',
    `- CLI：\`smartsub ${op.name.replace('.', ' ')}\``,
    `- MCP：\`${toolName(op.name)}\``,
    `- 属性：${op.readOnly ? '读取' : '修改/执行'}；${op.long ? '异步任务' : '直接返回'}`,
    '',
    '```json',
    JSON.stringify(
      (zodToJsonSchema as Function)(op.schema, { $refStrategy: 'none' }),
      null,
      2,
    ),
    '```',
    '',
  );
}
fs.writeFileSync('docs/docs/guides/automation-reference.md', lines.join('\n'));
